### ISSUE TITLE
handle diamond-style imports gracefully

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-schema-kotlin#117]
A diamond import follows the patter of schema A importing schemas B and C, which in turn both import schema D.  In this scenario, schema A transitively imports schema D twice, which the current implementation reports as an error.

A friendlier approach would be for the implementation to recognize that the duplicate types imported transitively from D aren't conflicting type definitions, they are simply redundant, and thereby permissible.  Rather than attempting to define equivalence between type definitions, it is likely sufficient to keep track of the schemaId (or perhaps the Authority + schemaId?) used to load each type, and if a type of the same name was loaded from the same schemaId, it is an allowable, redundant import, not a conflict.

**Comment by mwfpope** [comment]
This issue is a pain point for my team. We have a large schema, and we are trying to split it into multiple files. The problem is that we have some common types that we have defined, such as a UUID, that are used all over the place. It seems like there are workarounds (import aliases, import references directly in the type constraint rather than at the top of the file), but none of them solves the maintainability problem—they only move the sharp edges somewhere else.

I also gave some thought about how to solve this problem. Instead of trying to load the whole schema file at once, what if the AuthorityFilesystem could start by reading just the header (and imports) of the requested file, and then recursively read the header (and imports) from each referenced file, using that information to construct a directed graph (ideally a tree) of the imports.  Once the import graph has been constructed, it can start at the leaf nodes and read the type definitions, working its way up to the root node (the file that was originally requested) as each schema file has its particular import dependencies satisfied.

As an added benefit, this would allow easy detection of cycles in the dependencies, which could be used to prevent [issue #58].

**Comment by mwfpope** [comment]
I'm going to try implementing this enhancement by using structural equivalence of the type definitions. While not the only possible definition of equivalence, I believe this is the strictest possible definition of equivalence that will solve the diamond import problem.


Using structural equivalence of the type definition, this would be valid:
```
type::{
  name: positive_int,
  valid_values: range::[1, max],
  type: int,
}
type::{
  valid_values: range::[1, max],
  type: int,
  name: positive_int,
}
```

But this would not be valid. Even though the two definitions of `positive_int_container` would produce the same validation results, they are not structurally equivalent definitions.
```
type::{
  name: positive_int_container,
  fields: {
    my_positive_int: {
      valid_values: range::[1, max],
      type: int,
    }
  }
}
type::{
  name: positive_int,
  valid_values: range::[1, max],
  type: int,
}
type::{
  name: positive_int_container,
  fields: {
    my_positive_int: positive_int
  }
}
```

**Comment by pbcornell** [comment]
Hi Matthew,

Your use of the term "structural equivalence" is narrower than the other contexts I've heard it used in.  I think of structural equivalence as analogous to duck-typing:  it doesn't matter how two types are defined; if they both look and sound like a duck, they're both ducks.  I'd expect your two `positive_int_container` types to be considered structurally equivalent.

Perhaps what you're describing is "definitional(?) equivalence," or perhaps just "Ion equivalence":  two type definitions are equivalent if and only if their Ion/ISL are equal to each other.

What value does this provide over simply comparing the schemaId/typeName of two type definitions?  If you're wanting to allow the same type to be defined within multiple schemas, this sounds like a misfeature (i.e., duplicates have to be kept in sync or they diverge over time).  We do want to gracefully allow a redundant import of a type, but I think you're taking this idea one step further.  Help me understand the value in doing so?

**Comment by mwfpope** [comment]
You are correct—by "structural equivalence of the type definition", I was intending to say that the ISL of the type definitions are equal to each other. Perhaps I should have said "structural equivalence of the ISL" because I was trying to contrast it with functionally equivalent ISL (such as the `positive_int_container` example above).

I did realize that my approach would allow redundant types across multiple schemas, but I guess I was misunderstanding what constitutes a type. I had understood two types to be equal iff they would produce the same validation result for a given input, and so if the ISL of the type definition is equal, then it logically implies that the types are equal. Redundant types were not something that I was trying to do, but based on my understanding of types, it seemed like there was at most an insignificant difference between "redundant types" and "redundant imports of types".

On the other hand, if the equality of two types also requires that they come from the same schema, then there is a very significant distinction between "redundant type" and "redundant import of a type".

I will try to work on an implementation for redundant *imports* of types with this distinction in mind.

Do you think it would be worthwhile updating the Ion Specification to include some information about the definition of equality for ISL types?

**Comment by pbcornell** [comment]
> Do you think it would be worthwhile updating the Ion Specification to include some information about the definition of equality for ISL types?

Ideally (to restate some of the above):  two types are equal iff they produce the same validation result for all values, independent of how the types are expressed in ISL.  This is quite difficult to implement correctly when the `regex` constraint is used, and the `not` constraint presents challenges, too.  I'd say updating the spec would require more thought, and is beyond the scope of this issue.  One step in this direction at some point would be to provide a comparison feature based on the _shape_ of a type, but not by comparing any _value_ constraints (see #140).

To be clear:  if your intent is to add logic such that the following two type definitions may both be imported into a schema because they are "ISL-equivalent":

```
// file1.isl:
type::{
  name: positive_int,
  valid_values: range::[1, max],
  type: int,
}
```

```
// file2.isl:
type::{
  valid_values: range::[1, max],
  type: int,
  name: positive_int,
}
```

then I'd call this a misfeature, and think this library should continue to throw an exception in this case.  I believe the user is better off near- and long-term to consolidate these into a single definition of `positive_int`.

However, if this library included logic that gracefully ignored a redundant import (instead of throwing an exception, as it does today) based on schemaId/typeName, this issue could be resolved, and I suspect it would alleviate this pain point for your team.

Hope we're on the same page; let me know if we're not :)

**Comment by mwfpope** [comment]
We're on the same page.
