### ISSUE TITLE
add a type to a schema

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-schema-kotlin#73]
Would "add a type to a schema" fall under #46 or #47?  I have a use case for building the schema dynamically; right now my workaround is to keep a list of type definitions myself and rebuild the `Schema` object every time (which is pretty slow -- O(N^2) for adding N types)

_Originally posted by @mtcalvin in https://github.com/amzn/ion-schema-kotlin/issues/47#issuecomment-470241040_

**Comment by pbcornell** [comment]
@mtcalvin:  sounds a bit different than #46 and #47;  moving your question to this new issue for further discussion.

I think you're describing an API that would allow a new type to be "registered" with a schema, e.g.:
```kotlin
interface Schema {
    fun addType(isl: String)
    fun addType(isl: IonStruct)
}
```
Where the provided isl would be required to have a name.  Subsequent calls to `Schema.getType(String)` would return the type without rebuilding it from scratch (vs. the behavior of `Schema.newType(isl)`, which always builds from scratch).

However, I'm wondering whether the current APIs already meet your needs.  Two scenarios come to mind from your description:
- **_n_ static types, 1 dynamic type:**  use `IonSchemaSystem.loadSchema(id)` or `IonSchemaSystem.newSchema(isl)` to instantiate a Schema object with the static types, then call that object's `newType(isl)` to create the dynamic type (and dispose of it when no longer needed)
- **_n_ static types, >1 dynamic types:** use `IonSchemaSystem.newSchema(isl)` to instantiate a new Schema object that contains the dynamic types, and *imports* the static types from another schema

I agreed that it's wise to minimize the re-creation of static types.  Assuming one of the above options is reasonable, I'm not sure I understand the interest in adding a dynamic type to a schema;  in my mind, *dynamic* implies transient, short-lived.  Am I missing something?

**Comment by mtcalvin** [comment]
Thanks for opening this for discussion.  For context, IonSchema isn't directly exposed to consumers of my library.  Instead, consumers interact with an interface I've defined (which includes both type definitions and other application-specific data that is not IonSchema-related) and internally the library constructs IonSchema objects for validation purposes.

There are 2 cases I want to consider:

  1. When a user of my library is creating their schema, they may call my library's API (let's call it `createType` many times, and some of these may create types that depend on previously created types.  Providing a batch create doesn't really help here because the frontend of this library is an interactive DDL tool.  In this case, recreating the schema feels messy.
  2. When a user of my library wants to load a saved schema, my library needs to rehydrate the IonSchema `Schema` from my application-defined catalog.  I'm not too concerned about this because I can probably refactor the code to batch the type definitions and create the `Schema` object at the end.

Here is what I had imagined for case 1:

```java
Schema schema = iss.newSchema();
// ...

MyType createType(String name, IonStruct typeDefinition, /* other params irrelevant */) {
    // Perform some business logic / validation of non-ISL related params
    // ...
    Type type = schema.addType(typeDefinition);
    return new MyType(name, type, /* other params irrelevant to ISL */)
}
```

Here is what I am currently doing:

```java
List<IonStruct> typeDefs = new ArrayList();
Schema schema = iss.newSchema();
// ...

MyType createType(String name, IonStruct typeDefinition, /* other params irrelevant */) {
    // Perform some business logic / validation of non-ISL related params
    // ...
    typeDefs.add(typeDefinition);
    schema = iss.newSchema(typeDefs.iterator());
    return new MyType(name, schema.getType(name), /* other params irrelevant to ISL */)
}
```

If there is a better way to accomplish this with the existing API, or using a different feature besides `addType`, I'm happy to do it that way.

**Comment by pbcornell** [comment]
I see, thanks for clarifying.  Sounds like the second case you've identified aligns well with the current APIs and you have a path forward;  focusing on the first case.

I'm admittedly hesitant to make types and schemas mutable due to thread-safety considerations, as well as the surprising behavior doing so would introduce (e.g., "this value used to be valid for schema/type X, but it isn't anymore?  hmm...").  However, perhaps we could consider a persistent/immutable approach along the lines of [PCollections](https://pcollections.org/).  Schemas and Types would be immutable, but instead of:
```java
Type type = schema.addType(typeDefinition);
```
you'd call something like:
```java
Schema newSchema = schema.plus(typeDefinition);
Type type = newSchema.get(name);
```

Note that if `schema` already contains a type named "A", a new type definition named "A" would take its place in `newSchema`.

Would this meet your needs?

**Comment by mtcalvin** [comment]
>I'm admittedly hesitant to make types and schemas mutable [...]

Agreed on all of these points about mutability.  The PCollections approach sounds reasonable.

>Note that if schema already contains a type named "A", a new type definition named "A" would take its place in newSchema.

In my particular case, this isn't a problem, since my application already checks for existence before attempting to add a type, but the name `plus` doesn't imply overwriting, IMO.  I would expect an overwrite operation to be called `override` or `put` or something like that -- I'm not sure if Ion-related libraries have established a convention for that sort of thing.

**Comment by pbcornell** [comment]
Other Ion libraries don't have this pattern yet, but PCollection's `PMap.plus()` replaces an existing key, as does Kotlin's `Map.plus()`--I think that's enough convention to follow suit here.
